config/routes.rb
Rails.application.routes.draw do
  resources :participants
  resources :milestones
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/milestone.rb
class Milestone < ApplicationRecord
end

app/models/milestone_participant_weight.rb
class MilestoneParticipantWeight < ApplicationRecord
end

app/models/participant.rb
class Participant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :set_milestone, only: [:show, :edit, :update, :destroy]

  # GET /milestones
  # GET /milestones.json
  def index
    @milestones = Milestone.all
  end

  # GET /milestones/1
  # GET /milestones/1.json
  def show
  end

  # GET /milestones/new
  def new
    @milestone = Milestone.new
  end

  # GET /milestones/1/edit
  def edit
  end

  # POST /milestones
  # POST /milestones.json
  def create
    @milestone = Milestone.new(milestone_params)

    respond_to do |format|
      if @milestone.save
        format.html { redirect_to @milestone, notice: 'Milestone was successfully created.' }
        format.json { render :show, status: :created, location: @milestone }
      else
        format.html { render :new }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /milestones/1
  # PATCH/PUT /milestones/1.json
  def update
    respond_to do |format|
      if @milestone.update(milestone_params)
        format.html { redirect_to @milestone, notice: 'Milestone was successfully updated.' }
        format.json { render :show, status: :ok, location: @milestone }
      else
        format.html { render :edit }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /milestones/1
  # DELETE /milestones/1.json
  def destroy
    @milestone.destroy
    respond_to do |format|
      format.html { redirect_to milestones_url, notice: 'Milestone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_milestone
      @milestone = Milestone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def milestone_params
      params.require(:milestone).permit(:name, :desc, :target_date)
    end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name, :initials)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>M2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/milestones/_form.html.erb
<%= form_with(model: milestone, local: true) do |form| %>
  <% if milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>

      <ul>
      <% milestone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

  <div class="field">
    <%= form.label :target_date %>
    <%= form.date_select :target_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/milestones/edit.html.erb
<h1>Editing Milestone</h1>

<%= render 'form', milestone: @milestone %>

<%= link_to 'Show', @milestone %> |
<%= link_to 'Back', milestones_path %>

app/views/milestones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Milestones</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Target date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @milestones.each do |milestone| %>
      <tr>
        <td><%= milestone.name %></td>
        <td><%= milestone.desc %></td>
        <td><%= milestone.target_date %></td>
        <td><%= link_to 'Show', milestone %></td>
        <td><%= link_to 'Edit', edit_milestone_path(milestone) %></td>
        <td><%= link_to 'Destroy', milestone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Milestone', new_milestone_path %>

app/views/milestones/new.html.erb
<h1>New Milestone</h1>

<%= render 'form', milestone: @milestone %>

<%= link_to 'Back', milestones_path %>

app/views/milestones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @milestone.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @milestone.desc %>
</p>

<p>
  <strong>Target date:</strong>
  <%= @milestone.target_date %>
</p>

<%= link_to 'Edit', edit_milestone_path(@milestone) %> |
<%= link_to 'Back', milestones_path %>

app/views/participants/_form.html.erb
<%= form_with(model: participant, local: true) do |form| %>
  <% if participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :initials %>
    <%= form.text_field :initials %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Initials</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.name %></td>
        <td><%= participant.initials %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @participant.name %>
</p>

<p>
  <strong>Initials:</strong>
  <%= @participant.initials %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>